In [29]:
import pandas as pd

In [30]:
actas_nombres = ['actas_detalle_1.csv', 'actas_detalle_2.csv']

actas = pd.concat([pd.read_csv(acta, index_col='acta_detalle_id') for acta in actas_nombres])
actas.head()

,acta_id,diputado_nombre,persona_id,bloque,distrito_nombre,voto
acta_detalle_id,,,,,,
1085826,3761,ABDALA DE MATARAZZO Norma Amanda,,Frente Cívico por Santiago,Santiago del Estero,AFIRMATIVO
1085827,3761,ACERENZA Samanta María Celeste,,PRO,Buenos Aires,NEGATIVO
1085828,3761,AICEGA Juan,,PRO,Buenos Aires,NEGATIVO
1085829,3761,ALLENDE Walberto Enrique,,Todos Juntos por San Juan,San Juan,AFIRMATIVO
1085830,3761,ALONSO Laura Valeria,,Frente para la Victoria - PJ,Buenos Aires,AFIRMATIVO

In [31]:
bloques = pd.read_csv('bloques.csv')
bloques['diputado_nombre'] = bloques['diputado_apellido'] + bloques['diputado_nombres']
bloques = bloques.set_index('diputado_nombre', verify_integrity=True)
bloques.head()

,diputado_bloque,diputado_apellido,diputado_nombres,diputado_distrito,periodo
diputado_nombre,,,,,
AGUIRRE Hilda Clelia,BLOQUE FRENTE DE TODOS,AGUIRRE,Hilda Clelia,LA RIOJA,2019-2023
ALDERETE Juan Carlos,BLOQUE FRENTE DE TODOS,ALDERETE,Juan Carlos,BUENOS AIRES,2019-2023
ALIANIELLO Eugenia,BLOQUE FRENTE DE TODOS,ALIANIELLO,Eugenia,CHUBUT,2021-2025
ALLENDE Walberto,BLOQUE FRENTE DE TODOS,ALLENDE,Walberto,SAN JUAN,2021-2025
ALONSO Constanza María,BLOQUE FRENTE DE TODOS,ALONSO,Constanza María,BUENOS AIRES,2021-2025

In [32]:
expedientes_nombres = ['expedientes_1.csv', 'expedientes_2.csv']

expedientes = pd.concat([pd.read_csv(acta, index_col='acta_id') for acta in expedientes_nombres])
expedientes.head()

,numero,origen,anio,expediente,titulo,od
acta_id,,,,,,
424,27,S,2010,0027-S-2010,APROBACION DEL ACUERDO CON EL GOBIERNO DE RUMA...,1117.0
424,4222,D,2010,4222-D-2010,RESOLUCIONES EMITIDAS POR EL MINISTERIO DE DEF...,1143.0
424,4427,D,2010,4427-D-2010,EJECUCION DE LA PENA PRIVATIVA DE LA LIBERTAD ...,1264.0
424,25,S,2010,0025-S-2010,APROBACION DEL PROTOCOLO POR EL QUE SE ENMIEND...,1301.0
424,28,S,2010,0028-S-2010,PROTOCOLO DEL PACTO INTERNACIONAL DE DERECHOS ...,NaN

In [33]:
df = actas.join(expedientes, on='acta_id')
df = df[df['titulo'].notna()] # Filtro actas con titulo
df = df[df['diputado_nombre'].notna()] # Filtro detalles con diputado
df

,acta_id,diputado_nombre,persona_id,bloque,distrito_nombre,voto,numero,origen,anio,expediente,titulo,od
acta_detalle_id,,,,,,,,,,,,
1086083,3762,ABDALA DE MATARAZZO Norma Amanda,,Frente Cívico por Santiago,Santiago del Estero,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
1086084,3762,ACERENZA Samanta María Celeste,,PRO,Buenos Aires,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
1086085,3762,AICEGA Juan,,PRO,Buenos Aires,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
1086086,3762,ALLENDE Walberto Enrique,,Todos Juntos por San Juan,San Juan,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
1086087,3762,ALONSO Laura Valeria,,Frente para la Victoria - PJ,Buenos Aires,ABSTENCION,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1167806,3905,ZAMORA Claudia,,Frente Cívico por Santiago,Santiago del Estero,NEGATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN
1167807,3905,ZILIOTTO Sergio Raúl,,Justicialista,La Pampa,AFIRMATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN
1167807,3905,ZILIOTTO Sergio Raúl,,Justicialista,La Pampa,AFIRMATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN
1167808,3905,ZOTTOS Miguel Andrés Costas,,Justicialista,Salta,AFIRMATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN
1167808,3905,ZOTTOS Miguel Andrés Costas,,Justicialista,Salta,AFIRMATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN

In [34]:
bloques

,diputado_bloque,diputado_apellido,diputado_nombres,diputado_distrito,periodo
diputado_nombre,,,,,
AGUIRRE Hilda Clelia,BLOQUE FRENTE DE TODOS,AGUIRRE,Hilda Clelia,LA RIOJA,2019-2023
ALDERETE Juan Carlos,BLOQUE FRENTE DE TODOS,ALDERETE,Juan Carlos,BUENOS AIRES,2019-2023
ALIANIELLO Eugenia,BLOQUE FRENTE DE TODOS,ALIANIELLO,Eugenia,CHUBUT,2021-2025
ALLENDE Walberto,BLOQUE FRENTE DE TODOS,ALLENDE,Walberto,SAN JUAN,2021-2025
ALONSO Constanza María,BLOQUE FRENTE DE TODOS,ALONSO,Constanza María,BUENOS AIRES,2021-2025
...,...,...,...,...,...
OMODEO Paula,BLOQUE CREO,OMODEO,Paula,TUCUMÁN,2021-2025
FIGUEROA Rolando,BLOQUE MOVIMIENTO POPULAR NEUQUINO,FIGUEROA,Rolando,NEUQUÉN,2021-2025
DEL PLA Romina,BLOQUE PARTIDO OBRERO EN EL FRENTE DE IZQUIERD...,DEL PLA,Romina,BUENOS AIRES,2021-2025
LOPEZ MURPHY Ricardo Hipólito,BLOQUE REPUBLICANOS UNIDOS,LOPEZ MURPHY,Ricardo Hipólito,CIUDAD AUTÓNOMA DE BUENOS AIRES,2021-2025
CASTETS Laura Carolina,BLOQUE VALORES REPUBLICANOS,CASTETS,Laura Carolina,SANTA FE,2019-2023

In [35]:
df = df.join(bloques, on='diputado_nombre')
df.head()

,acta_id,diputado_nombre,persona_id,bloque,distrito_nombre,voto,numero,origen,anio,expediente,titulo,od,diputado_bloque,diputado_apellido,diputado_nombres,diputado_distrito,periodo
acta_detalle_id,,,,,,,,,,,,,,,,,
1086083,3762,ABDALA DE MATARAZZO Norma Amanda,,Frente Cívico por Santiago,Santiago del Estero,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN
1086084,3762,ACERENZA Samanta María Celeste,,PRO,Buenos Aires,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN
1086085,3762,AICEGA Juan,,PRO,Buenos Aires,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN
1086086,3762,ALLENDE Walberto Enrique,,Todos Juntos por San Juan,San Juan,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN
1086087,3762,ALONSO Laura Valeria,,Frente para la Victoria - PJ,Buenos Aires,ABSTENCION,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df['diputado_bloque'].unique()

array([nan, 'BLOQUE FRENTE DE TODOS', 'BLOQUE IDENTIDAD BONAERENSE',
       'BLOQUE COALICIÓN CÍVICA', 'BLOQUE EVOLUCIÓN RADICAL',
       'BLOQUE U.C.R.',
       'BLOQUE PTS - FRENTE DE IZQUIERDA Y DE TRABAJADORES-UNIDAD',
       'BLOQUE FRENTE PRO', 'BLOQUE ENCUENTRO FEDERAL',
       'BLOQUE AVANZAR SAN LUIS'], dtype=object)