In [133]:
import pandas as pd

In [134]:
actas_nombres = ['actas_detalle_1.csv', 'actas_detalle_2.csv']

actas = pd.concat([pd.read_csv(acta, index_col='acta_detalle_id') for acta in actas_nombres])
actas.head()

,acta_id,diputado_nombre,persona_id,bloque,distrito_nombre,voto
acta_detalle_id,,,,,,
1085826,3761,ABDALA DE MATARAZZO Norma Amanda,,Frente Cívico por Santiago,Santiago del Estero,AFIRMATIVO
1085827,3761,ACERENZA Samanta María Celeste,,PRO,Buenos Aires,NEGATIVO
1085828,3761,AICEGA Juan,,PRO,Buenos Aires,NEGATIVO
1085829,3761,ALLENDE Walberto Enrique,,Todos Juntos por San Juan,San Juan,AFIRMATIVO
1085830,3761,ALONSO Laura Valeria,,Frente para la Victoria - PJ,Buenos Aires,AFIRMATIVO

In [135]:
def APELLIDOS_nombre(nombres):
    if not isinstance(nombres, list):
        return nombres
    
    res = ''
    for nombre in nombres:
        res +=  ' ' + nombre
        if nombre.upper() != nombre:
            break
    return res.strip()

In [136]:
# actas['diputado_nombre'] = actas['diputado_nombre'].str.split(' ').apply(APELLIDOS_nombre)

In [137]:
bloques = pd.read_csv('bloques.csv')
bloques['diputado_nombre'] = bloques['diputado_apellido'] + ' ' + bloques['diputado_nombres'].str.strip() # .str.split(' ').apply(lambda r: r[0])
bloques = bloques.set_index('diputado_nombre', verify_integrity=True)
bloques.head()

,diputado_bloque,diputado_apellido,diputado_nombres,diputado_distrito,periodo
diputado_nombre,,,,,
AGUIRRE Hilda Clelia,BLOQUE FRENTE DE TODOS,AGUIRRE,Hilda Clelia,LA RIOJA,2019-2023
ALDERETE Juan Carlos,BLOQUE FRENTE DE TODOS,ALDERETE,Juan Carlos,BUENOS AIRES,2019-2023
ALIANIELLO Eugenia,BLOQUE FRENTE DE TODOS,ALIANIELLO,Eugenia,CHUBUT,2021-2025
ALLENDE Walberto,BLOQUE FRENTE DE TODOS,ALLENDE,Walberto,SAN JUAN,2021-2025
ALONSO Constanza María,BLOQUE FRENTE DE TODOS,ALONSO,Constanza María,BUENOS AIRES,2021-2025

In [138]:
expedientes_nombres = ['expedientes_1.csv', 'expedientes_2.csv']

expedientes = pd.concat([pd.read_csv(acta, index_col='acta_id') for acta in expedientes_nombres])
expedientes.head()

,numero,origen,anio,expediente,titulo,od
acta_id,,,,,,
424,27,S,2010,0027-S-2010,APROBACION DEL ACUERDO CON EL GOBIERNO DE RUMA...,1117.0
424,4222,D,2010,4222-D-2010,RESOLUCIONES EMITIDAS POR EL MINISTERIO DE DEF...,1143.0
424,4427,D,2010,4427-D-2010,EJECUCION DE LA PENA PRIVATIVA DE LA LIBERTAD ...,1264.0
424,25,S,2010,0025-S-2010,APROBACION DEL PROTOCOLO POR EL QUE SE ENMIEND...,1301.0
424,28,S,2010,0028-S-2010,PROTOCOLO DEL PACTO INTERNACIONAL DE DERECHOS ...,NaN

In [139]:
df = actas.join(expedientes, on='acta_id')
df = df[df['titulo'].notna()] # Filtro actas con titulo
df = df[df['diputado_nombre'].notna()] # Filtro detalles con diputado
df

,acta_id,diputado_nombre,persona_id,bloque,distrito_nombre,voto,numero,origen,anio,expediente,titulo,od
acta_detalle_id,,,,,,,,,,,,
1086083,3762,ABDALA DE MATARAZZO Norma Amanda,,Frente Cívico por Santiago,Santiago del Estero,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
1086084,3762,ACERENZA Samanta María Celeste,,PRO,Buenos Aires,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
1086085,3762,AICEGA Juan,,PRO,Buenos Aires,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
1086086,3762,ALLENDE Walberto Enrique,,Todos Juntos por San Juan,San Juan,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
1086087,3762,ALONSO Laura Valeria,,Frente para la Victoria - PJ,Buenos Aires,ABSTENCION,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1167806,3905,ZAMORA Claudia,,Frente Cívico por Santiago,Santiago del Estero,NEGATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN
1167807,3905,ZILIOTTO Sergio Raúl,,Justicialista,La Pampa,AFIRMATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN
1167807,3905,ZILIOTTO Sergio Raúl,,Justicialista,La Pampa,AFIRMATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN
1167808,3905,ZOTTOS Miguel Andrés Costas,,Justicialista,Salta,AFIRMATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN
1167808,3905,ZOTTOS Miguel Andrés Costas,,Justicialista,Salta,AFIRMATIVO,120.0,S,2018.0,0120-S-2018,Proyecto de ley en revisión po el cual se apru...,NaN

In [140]:
bloques_nombres = set(bloques.index)
actas_nombres = set(actas['diputado_nombre'])

In [141]:
bloques_nombres - actas_nombres

{'AGOST CARREÑO Oscar',
 'AGUIRRE Manuel Ignacio',
 'AJMECHET Sabrina',
 'ALIANIELLO Eugenia',
 'ALLENDE Walberto',
 'ALONSO Constanza María',
 'AMAYA Domingo Luis',
 'APARICIO Alicia N.',
 'ARJOL Martín',
 'ARRICAU Carolina Natalia',
 'ARROYO Daniel',
 'ASCARATE Lidia Inés',
 'ASSEFF Alberto',
 'AUBONE Ana Fabiola',
 'BACHEY Karina Ethel',
 'BALDASSI Héctor W.',
 'BANFI Karina',
 'BARBARO Héctor "Cacho"',
 'BARLETTA Mario',
 'BENEDETTI Atilio',
 'BERHONGARAY Martín Antonio',
 'BERMEJO Adolfo',
 'BERTOLDI Tanya',
 'BESANA Gabriela',
 'BORDA Fabian Antonio',
 'BORMIOLI Lisandro',
 'BORREGO Victoria',
 'BRAMBILLA Sofia',
 'BROUWER DE KONING Gabriela',
 'CALIVA Lía Verónica',
 'CALLETTI Pamela',
 'CANTERO Carlos',
 'CAPARROS Mabel Luisa',
 'CARASSO Marcos Gustavo',
 'CARBAJAL Fernando',
 'CARNAGHI Guillermo Oscar',
 'CARRO José',
 'CERVI Pablo',
 'CHAHER Leila',
 'CHAHLA Rossana',
 'CHOMIAK María Luisa',
 'CHUMPITAZ Gabriel Felipe',
 'COBOS Julio',
 'COLI Marcela',
 'CORNEJO Virginia',
 'COSTA Anahí',
 'DANTAS Pedro Cristian',
 'DE LA SOTA Natalia',
 'DE LOREDO Rodrigo',
 'DE MARCHI Omar',
 'DEL PLA Romina',
 'DOMINGO Agustín',
 'ESPERT José Luis',
 'ESPIL Santiago Eugenio',
 'ESTEVEZ Enrique',
 'ESTRADA Emiliano',
 'FEIN Mónica',
 'FERNANDEZ PATRI Ramiro',
 'FERNÁNDEZ Agustín',
 'FERNÁNDEZ Carlos Alberto',
 'FERNÁNDEZ Eduardo',
 'FERRARO Maximiliano',
 'FIGUEROA CASAS Germana',
 'FIGUEROA Rolando',
 'FINOCCHIARO Alejandro',
 'FRADE Mónica Edith',
 'GALIMBERTI Pedro Jorge',
 'GARCÍA ARESCA Ignacio',
 'GARCÍA Ximena',
 'GARCÍA de LUCA Sebastián',
 'GOLLAN Daniel',
 'GONZÁLEZ Gustavo',
 'GUTIÉRREZ Carlos Mario',
 'GUTIÉRREZ Ramiro',
 'HEIN Gustavo René',
 'HELLER Carlos',
 'HERNANDEZ Estela',
 'HERRERA Ricardo',
 'IPARRAGUIRRE Rogelio',
 'JOURY María de las Mercedes',
 'KLIPAUKA LEWTAK Florencia',
 'LACIAR Susana Alicia',
 'LATORRE Jimena',
 'LEDESMA Tomás',
 'LEIVA Aldo Adolfo',
 'LENA Gabriela',
 'LITZA Mónica',
 'LOMBARDI Hernán',
 'LOPEZ MURPHY Ricardo Hipólito',
 'LÓPEZ RODRÍGUEZ Dante',
 'MANES Facundo',
 'MANZI Rubén',
 'MARINO Juan',
 'MARTÍN Juan',
 'MARTÍNEZ Dolores',
 'MARTÍNEZ María Rosa',
 'MARTÍNEZ Álvaro',
 'MARZIOTTA Gisela',
 'MARÍN Varinia Lis',
 'MASTALER Magali',
 'MILEI Javier Gerardo',
 'MILMAN Gerardo',
 'MIRABELLA Roberto',
 'MONTI Francisco',
 'MORAN Micaela',
 'MOREAU Leopoldo',
 'MOYANO NILDA',
 'NEDER Estela Mary',
 'NIERI Lisandro',
 'OCAÑA Graciela',
 'OLIVETO LAGO Paula',
 'OMODEO Paula',
 'ORMACHEA Claudia Beatriz',
 'OSUNA Blanca Inés',
 'PALAZZO Sergio Omar',
 'PAPONET Liliana',
 'PAROLA María Graciela',
 'PEDRALI Gabriela',
 'PEREYRA Julio',
 'PEREZ ARAUJO Hernan',
 'PIPARO Carolina',
 'POLINI Juan Carlos',
 'PROPATO Agustina Lucrecia',
 'PÉREZ PLAZA Eber Albano',
 'QUIROZ Marilú',
 'RANDAZZO Florencio',
 'REY María Luján',
 'REYES Roxana',
 'REZINOVSKY Dina',
 'RITONDO Cristian Adrián',
 'RIZZOTTI Jorge "Colo"',
 'RODRIGUEZ Alejandro "Topo"',
 'RODRÍGUEZ MACHADO Laura',
 'ROMERO Ana Clara',
 'SALVADOR Sebastián Nicolás',
 'SAND Nancy',
 'SANTILLI Diego',
 'SANTORO Leandro',
 'SARAPURA Natalia Silvina',
 'SILEY Vanesa Raquel',
 'SOTOLANO María',
 'SOUTO Natalia Marcela',
 'STOLBIZER Margarita',
 'SÁNCHEZ Francisco',
 'SÁNCHEZ Roberto Antonio',
 'TACCETTA Matias',
 'TAILHADE Rodolfo',
 'TAVELA Danya',
 'TEJEDA María Victoria',
 'TETAZ Martín Alberto',
 'TONIOLLI Eduardo',
 'TORTORIELLO Aníbal',
 'VALDES Eduardo Félix',
 'VARA Jorge',
 'VARGAS MATYI Brenda',
 'VERASAY Pamela Fernanda',
 'VERÓN Jorge Guillermo',
 'VESSVESSIAN Paola',
 'VIDAL Claudio Orlando',
 'VIDAL María Eugenia',
 'VILCA Alejandro',
 'VILLARRUEL Victoria',
 'YACOBITTI Emiliano Benjamín',
 'YAMBRÚN Liliana Patricia',
 'YAPOR Lucio',
 'YUTROVIC Carolina',
 'ZABALA CHACUR Natalia',
 'ZAPATA Carlos Raúl',
 'ZARACHO Natalia',
 'ÁNTOLA Marcela'}

In [142]:
df = df.join(bloques, on='diputado_nombre')
df.head()

,acta_id,diputado_nombre,persona_id,bloque,distrito_nombre,voto,numero,origen,anio,expediente,titulo,od,diputado_bloque,diputado_apellido,diputado_nombres,diputado_distrito,periodo
acta_detalle_id,,,,,,,,,,,,,,,,,
1086083,3762,ABDALA DE MATARAZZO Norma Amanda,,Frente Cívico por Santiago,Santiago del Estero,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN
1086084,3762,ACERENZA Samanta María Celeste,,PRO,Buenos Aires,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN
1086085,3762,AICEGA Juan,,PRO,Buenos Aires,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN
1086086,3762,ALLENDE Walberto Enrique,,Todos Juntos por San Juan,San Juan,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN
1086087,3762,ALONSO Laura Valeria,,Frente para la Victoria - PJ,Buenos Aires,ABSTENCION,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
interbloques = pd.read_csv('interbloques.csv')
interbloques['diputado_nombre'] = interbloques['diputado_apellido'] + ' ' + interbloques['diputado_nombre'].str.strip() # .str.split(' ').apply(lambda r: r[0])

interbloques = interbloques.set_index('diputado_nombre', verify_integrity=True)
interbloques

,interbloque,diputado_apellido,diputado_distrito,diputado_bloque,periodo
diputado_nombre,,,,,
AGOST CARREÑO Oscar,INTERBLOQUE JUNTOS POR EL CAMBIO,AGOST CARREÑO,CÓRDOBA,FRENTE PRO,2021-2025
AGUIRRE Manuel Ignacio,INTERBLOQUE JUNTOS POR EL CAMBIO,AGUIRRE,CORRIENTES,U.C.R.,2021-2025
AJMECHET Sabrina,INTERBLOQUE JUNTOS POR EL CAMBIO,AJMECHET,CIUDAD AUTÓNOMA DE BUENOS AIRES,FRENTE PRO,2021-2025
AMAYA Domingo Luis,INTERBLOQUE JUNTOS POR EL CAMBIO,AMAYA,TUCUMÁN,ENCUENTRO FEDERAL,2019-2023
ANGELINI Federico,INTERBLOQUE JUNTOS POR EL CAMBIO,ANGELINI,SANTA FE,FRENTE PRO,2019-2023
...,...,...,...,...,...
FERNÁNDEZ Carlos Alberto,INTERBLOQUE PROVINCIAS UNIDAS,FERNÁNDEZ,MISIONES,FRENTE DE LA CONCORDIA MISIONERO,2021-2025
SARTORI Diego Horacio,INTERBLOQUE PROVINCIAS UNIDAS,SARTORI,MISIONES,FRENTE DE LA CONCORDIA MISIONERO,2019-2023
MILEI Javier Gerardo,INTERBLOQUE LA LIBERTAD AVANZA,MILEI,CIUDAD AUTÓNOMA DE BUENOS AIRES,LA LIBERTAD AVANZA,2021-2025
PIPARO Carolina,INTERBLOQUE LA LIBERTAD AVANZA,PIPARO,BUENOS AIRES,BUENOS AIRES LIBRE,2021-2025
VILLARRUEL Victoria,INTERBLOQUE LA LIBERTAD AVANZA,VILLARRUEL,CIUDAD AUTÓNOMA DE BUENOS AIRES,LA LIBERTAD AVANZA,2021-2025

In [144]:
df = df.join(interbloques['interbloque'], on='diputado_nombre')
df.head()

,acta_id,diputado_nombre,persona_id,bloque,distrito_nombre,voto,numero,origen,anio,expediente,titulo,od,diputado_bloque,diputado_apellido,diputado_nombres,diputado_distrito,periodo,interbloque
acta_detalle_id,,,,,,,,,,,,,,,,,,
1086083,3762,ABDALA DE MATARAZZO Norma Amanda,,Frente Cívico por Santiago,Santiago del Estero,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1086084,3762,ACERENZA Samanta María Celeste,,PRO,Buenos Aires,AUSENTE,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1086085,3762,AICEGA Juan,,PRO,Buenos Aires,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1086086,3762,ALLENDE Walberto Enrique,,Todos Juntos por San Juan,San Juan,AFIRMATIVO,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1086087,3762,ALONSO Laura Valeria,,Frente para la Victoria - PJ,Buenos Aires,ABSTENCION,3337.0,D,2017.0,3337-D-2017,"DIA NACIONAL DEL MOVIMIENTO ESTUDIANTIL"". SE I...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
df.to_parquet('data.parquet')